name: XML MSW binaries

on:
  workflow_dispatch:

jobs:
  build-xml-libs:
    name: Build XML binaries
    runs-on: ubuntu-latest
    container: debian:stable-slim

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 32 Bits
            host: i686-w64-mingw32
          - name: 64 Bits
            host: x86_64-w64-mingw32

    env:
      HOST: ${{ matrix.host }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tools
        run: |
          apt-get update -qq
          arch=`echo $HOST | sed -e 's/-w64-mingw32$//;s/_/-/'`
          apt-get install -qq --no-install-recommends g++-mingw-w64-$arch make pkg-config wget

      - name: Build
        run: |
          # sudo doesn't work and is not necessary inside a container, so don't use it.
          SUDO=env ./scripts/install_deps.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: xmllibs-${{ matrix.host }}
          path: /usr/local
          if-no-files-found: error
